packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - '@strangecyan/vignette-cli@0.4.1'
  - '@strangecyan/vignette-core@0.4.1'
  - '@strangecyan/vignette-frame@0.4.1'
  - '@strangecyan/vignette-moq@0.4.1'
  - '@strangecyan/vignette-target-dom@0.4.1'
  - '@strangecyan/vignette-target-obs@0.4.1'
  - '@strangecyan/vignette-vite@0.4.1'
  - '@strangecyan/vignette@0.4.1'
